// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package github.com.hlx.kvservice.grpc;

public final class FTKVService {
  private FTKVService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenSessionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenSessionReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\"J\n\022OpenSessionRequest" +
      "\022\020\n\010password\030\001 \001(\t\022\"\n\014request_type\030\002 \001(\016" +
      "2\014.RequestType\"B\n\020OpenSessionReply\022\022\n\nse" +
      "ssion_id\030\001 \001(\t\022\032\n\010err_code\030\002 \001(\0162\010.ErrCo" +
      "de\"c\n\rUpdateRequest\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t\022\"\n\014request_type\030\003 \001(\0162\014.RequestT" +
      "ype\022\022\n\nsession_id\030\004 \001(\t\")\n\013UpdateReply\022\032" +
      "\n\010err_code\030\001 \001(\0162\010.ErrCode\"Q\n\nGetRequest" +
      "\022\013\n\003key\030\001 \001(\t\022\022\n\nsession_id\030\002 \001(\t\022\"\n\014req" +
      "uest_type\030\003 \001(\0162\014.RequestType\"5\n\010GetRepl" +
      "y\022\r\n\005value\030\001 \001(\t\022\032\n\010err_code\030\002 \001(\0162\010.Err" +
      "Code*t\n\007ErrCode\022\020\n\014WRONG_LEADER\020\000\022\006\n\002OK\020" +
      "\001\022\n\n\006NO_KEY\020\002\022\023\n\017INVALID_SESSION\020\003\022\030\n\024IN" +
      "VALID_REQUEST_TYPE\020\004\022\024\n\020INVALID_PASSWORD" +
      "\020\005*I\n\013RequestType\022\020\n\014OPEN_SESSION\020\000\022\007\n\003G" +
      "ET\020\001\022\007\n\003PUT\020\002\022\n\n\006APPEND\020\003\022\n\n\006DELETE\020\0042\210\001" +
      "\n\010KVServer\0225\n\013OpenSession\022\023.OpenSessionR" +
      "equest\032\021.OpenSessionReply\022\035\n\003Get\022\013.GetRe" +
      "quest\032\t.GetReply\022&\n\006Update\022\016.UpdateReque" +
      "st\032\014.UpdateReplyB.\n\035github.com.hlx.kvser" +
      "vice.grpcB\013FTKVServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OpenSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenSessionRequest_descriptor,
        new java.lang.String[] { "Password", "RequestType", });
    internal_static_OpenSessionReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OpenSessionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenSessionReply_descriptor,
        new java.lang.String[] { "SessionId", "ErrCode", });
    internal_static_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateRequest_descriptor,
        new java.lang.String[] { "Key", "Value", "RequestType", "SessionId", });
    internal_static_UpdateReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReply_descriptor,
        new java.lang.String[] { "ErrCode", });
    internal_static_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRequest_descriptor,
        new java.lang.String[] { "Key", "SessionId", "RequestType", });
    internal_static_GetReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReply_descriptor,
        new java.lang.String[] { "Value", "ErrCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
