// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package github.com.hlx.kvservice.grpc;

public interface GetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>.ErrCode err_code = 2;</code>
   * @return The enum numeric value on the wire for errCode.
   */
  int getErrCodeValue();
  /**
   * <code>.ErrCode err_code = 2;</code>
   * @return The errCode.
   */
  github.com.hlx.kvservice.grpc.ErrCode getErrCode();
}
