// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package github.com.hlx.kvservice.grpc;

public interface OpenSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OpenSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>.RequestType request_type = 2;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  int getRequestTypeValue();
  /**
   * <code>.RequestType request_type = 2;</code>
   * @return The requestType.
   */
  github.com.hlx.kvservice.grpc.RequestType getRequestType();
}
