// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package github.com.hlx.kvservice.grpc;

public interface OpenSessionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OpenSessionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>.ErrCode err_code = 2;</code>
   * @return The enum numeric value on the wire for errCode.
   */
  int getErrCodeValue();
  /**
   * <code>.ErrCode err_code = 2;</code>
   * @return The errCode.
   */
  github.com.hlx.kvservice.grpc.ErrCode getErrCode();
}
