// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package github.com.hlx.kvservice.grpc;

/**
 * Protobuf enum {@code RequestType}
 */
public enum RequestType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OPEN_SESSION = 0;</code>
   */
  OPEN_SESSION(0),
  /**
   * <code>GET = 1;</code>
   */
  GET(1),
  /**
   * <code>PUT = 2;</code>
   */
  PUT(2),
  /**
   * <code>APPEND = 3;</code>
   */
  APPEND(3),
  /**
   * <code>DELETE = 4;</code>
   */
  DELETE(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OPEN_SESSION = 0;</code>
   */
  public static final int OPEN_SESSION_VALUE = 0;
  /**
   * <code>GET = 1;</code>
   */
  public static final int GET_VALUE = 1;
  /**
   * <code>PUT = 2;</code>
   */
  public static final int PUT_VALUE = 2;
  /**
   * <code>APPEND = 3;</code>
   */
  public static final int APPEND_VALUE = 3;
  /**
   * <code>DELETE = 4;</code>
   */
  public static final int DELETE_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RequestType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RequestType forNumber(int value) {
    switch (value) {
      case 0: return OPEN_SESSION;
      case 1: return GET;
      case 2: return PUT;
      case 3: return APPEND;
      case 4: return DELETE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RequestType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
          public RequestType findValueByNumber(int number) {
            return RequestType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return github.com.hlx.kvservice.grpc.FTKVService.getDescriptor().getEnumTypes().get(1);
  }

  private static final RequestType[] VALUES = values();

  public static RequestType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RequestType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:RequestType)
}

