// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package github.com.hlx.kvservice.grpc;

public interface UpdateReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ErrCode err_code = 1;</code>
   * @return The enum numeric value on the wire for errCode.
   */
  int getErrCodeValue();
  /**
   * <code>.ErrCode err_code = 1;</code>
   * @return The errCode.
   */
  github.com.hlx.kvservice.grpc.ErrCode getErrCode();
}
