// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package hlx.examples.helloworld.grpc;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_OpenSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_OpenSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_OpenSessionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_OpenSessionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\"\034\n\014HelloR" +
      "equest\022\014\n\004name\030\001 \001(\t\"8\n\022OpenSessionReque" +
      "st\022\025\n\010password\030\001 \001(\tH\000\210\001\001B\013\n\t_password\"Z" +
      "\n\nHelloReply\022\017\n\007message\030\001 \001(\t\022(\n\terrorCo" +
      "de\030\002 \001(\0162\025.helloworld.ErrorCode\022\021\n\terror" +
      "Info\030\003 \001(\t\"b\n\020OpenSessionReply\022\021\n\tsessio" +
      "nId\030\001 \001(\t\022(\n\terrorCode\030\002 \001(\0162\025.helloworl" +
      "d.ErrorCode\022\021\n\terrorInfo\030\003 \001(\t*;\n\tErrorC" +
      "ode\022\020\n\014WRONG_LEADER\020\000\022\006\n\002OK\020\001\022\024\n\020INVALID" +
      "_PASSWORD\020\0022\230\001\n\007Greeter\022>\n\010SayHello\022\030.he" +
      "lloworld.HelloRequest\032\026.helloworld.Hello" +
      "Reply\"\000\022M\n\013OpenSession\022\036.helloworld.Open" +
      "SessionRequest\032\034.helloworld.OpenSessionR" +
      "eply\"\000B1\n\034hlx.examples.helloworld.grpcB\017" +
      "HelloWorldProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_helloworld_OpenSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_OpenSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_OpenSessionRequest_descriptor,
        new java.lang.String[] { "Password", "Password", });
    internal_static_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloReply_descriptor,
        new java.lang.String[] { "Message", "ErrorCode", "ErrorInfo", });
    internal_static_helloworld_OpenSessionReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_OpenSessionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_OpenSessionReply_descriptor,
        new java.lang.String[] { "SessionId", "ErrorCode", "ErrorInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
