// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package hlx.examples.helloworld.grpc;

public interface OpenSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.OpenSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string password = 1;</code>
   * @return Whether the password field is set.
   */
  boolean hasPassword();
  /**
   * <code>optional string password = 1;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 1;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
